modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="laboratory"
version="1.6.0"
displayName="Laboratory"
credits="Created using mod CrimsonSteve MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="����, MCreator"

[[dependencies.laboratory]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




